/**
 * New Unit System - Elemental Battlegrounds
 * Integrates all new units and abilities from fusions_complete.json
 */

// Base Tier 1 units (available in shop)
const BASE_TIER1_UNITS = [
  'Fire', 'Water', 'Earth', 'Air', 'Gear', 'Chip', 'Lightning', 'Sand', 'Mist', 'Ash',
  'Drone', 'Nanobot', 'Turret', 'Processor', 'Flora', 'Quake', 'Zephyr', 'Frost',
  'Firewall', 'Cyborg', 'Quantum', 'DroneSwarm'
];

// New comprehensive unit definitions
const NEW_UNIT_DEFINITIONS = {
  // Base Tier 1 Units
  'Fire': { class: 'Elemental', attack: 1, health: 2, emoji: '🔥', elements: ['Fire'], tier: 1 },
  'Water': { class: 'Elemental', attack: 1, health: 2, emoji: '💧', elements: ['Water'], tier: 1 },
  'Earth': { class: 'Elemental', attack: 1, health: 2, emoji: '🌱', elements: ['Earth'], tier: 1 },
  'Air': { class: 'Elemental', attack: 1, health: 2, emoji: '💨', elements: ['Air'], tier: 1 },
  'Gear': { class: 'Tech', attack: 1, health: 3, emoji: '⚙️', elements: ['Tech'], tier: 1 },
  'Chip': { class: 'Tech', attack: 2, health: 2, emoji: '🔌', elements: ['Tech'], tier: 1 },
  'Lightning': { class: 'Elemental', attack: 2, health: 1, emoji: '⚡', elements: ['Lightning'], startAttackBonus: 1, tier: 1 },
  'Sand': { class: 'Elemental', attack: 1, health: 3, emoji: '🏜️', elements: ['Sand'], afterBattleHealthBonus: 1, tier: 1 },
  'Mist': { class: 'Elemental', attack: 1, health: 2, emoji: '🌫️', elements: ['Mist'], reduceIncomingAttack: 1, tier: 1 },
  'Ash': { class: 'Elemental', attack: 2, health: 1, emoji: '♨️', elements: ['Ash'], burnEffect: 1, tier: 1 },
  'Drone': { class: 'Tech', attack: 1, health: 2, emoji: '🛸', elements: ['Drone'], gainAttackOnKill: 1, tier: 1 },
  'Nanobot': { class: 'Tech', attack: 1, health: 2, emoji: '🧬', elements: ['Nanobot'], healHero: 1, tier: 1 },
  'Turret': { class: 'Tech', attack: 3, health: 1, emoji: '🔫', elements: ['Turret'], tier: 1 },
  'Processor': { class: 'Tech', attack: 0, health: 4, emoji: '💻', elements: ['Processor'], boardLimitBonus: 1, tier: 1 },
  'Flora': { class: 'Elemental', attack: 1, health: 3, emoji: '🌿', elements: ['Flora'], healHero: 1, tier: 1 },
  'Quake': { class: 'Elemental', attack: 2, health: 3, emoji: '⛰️', elements: ['Quake'], aoeDamage: 1, tier: 1 },
  'Zephyr': { class: 'Elemental', attack: 1, health: 4, emoji: '🍃', elements: ['Zephyr'], startAttackBonus: 2, tier: 1 },
  'Frost': { class: 'Elemental', attack: 1, health: 4, emoji: '❄️', elements: ['Frost'], reduceIncomingAttack: 1, tier: 1 },
  'Firewall': { class: 'Tech', attack: 1, health: 4, emoji: '🛡️', elements: ['Firewall'], reduceIncomingAttackAll: 1, tier: 1 },
  'Cyborg': { class: 'Tech', attack: 3, health: 3, emoji: '🦾', elements: ['Cyborg'], healHero: 1, tier: 1 },
  'Quantum': { class: 'Tech', attack: 2, health: 2, emoji: '⚛️', elements: ['Quantum'], survivorDamageBonus: 1, tier: 1 },
  'DroneSwarm': { class: 'Tech', attack: 2, health: 1, emoji: '🪰', elements: ['DroneSwarm'], gainAttackOnKill: 2, tier: 1 },
  
  // Tier 2 Units (from fusions_complete.json)
  'Lava': { class: 'Elemental', attack: 6, health: 6, emoji: '🌋', elements: ['Fire', 'Fire'], tier: 2, taunt: true, deathrattle: 'deal3ToTwoRandom' },
  'Steam': { class: 'Elemental', attack: 5, health: 5, emoji: '♨️', elements: ['Fire', 'Water'], tier: 2, afterPlayFireWater: '+1/+1' },
  'Magma': { class: 'Elemental', attack: 7, health: 5, emoji: '🖻', elements: ['Fire', 'Earth'], tier: 2, afterAttackSurvive: '+1Attack' },
  'Smoke': { class: 'Elemental', attack: 3, health: 7, emoji: '💨', elements: ['Fire', 'Air'], tier: 2, missChance: 0.5 },
  'Tide': { class: 'Elemental', attack: 4, health: 7, emoji: '🌊', elements: ['Water', 'Water'], tier: 2, startOfCombat: 'pushEnemiesBack' },
  'Mud': { class: 'Elemental', attack: 2, health: 8, emoji: '🟫', elements: ['Water', 'Earth'], tier: 2, taunt: true, endOfTurn: 'heal2' },
  'Mist': { class: 'Elemental', attack: 3, health: 6, emoji: '🌫️', elements: ['Water', 'Air'], tier: 2, stealth: true, endOfCombat: '+2Armor' },
  'Stone': { class: 'Elemental', attack: 3, health: 9, emoji: '🪨', elements: ['Earth', 'Earth'], tier: 2, taunt: true, deathrattle: '+2ArmorAdjacent' },
  'Sandstorm': { class: 'Elemental', attack: 5, health: 4, emoji: '🌪️', elements: ['Earth', 'Air'], tier: 2, endOfTurn: 'deal1ToAllEnemies' },
  'Gale': { class: 'Elemental', attack: 5, health: 5, emoji: '🌪️', elements: ['Air', 'Air'], tier: 2, windfury: true },
  'Android': { class: 'Tech', attack: 4, health: 6, emoji: '🤖', elements: ['Gear', 'Gear'], tier: 2, mech: true, startOfCombat: '+1/+1OtherMechs' },
  'Automaton': { class: 'Tech', attack: 3, health: 7, emoji: '🦾', elements: ['Gear', 'Chip'], tier: 2, afterPlayTech: 'refresh' },
  'AI Core': { class: 'Tech', attack: 2, health: 5, emoji: '🧠', elements: ['Chip', 'Chip'], tier: 2, afterSurviveTurn: '+2/+2' },
  
  // Tier 3 Units (Tier2+Tier1 combinations)
  'Foundry': { class: 'Elemental', attack: 10, health: 8, emoji: '🏭', elements: ['Lava', 'Fire'], tier: 3, deathrattle: 'summon3/5Golem' },
  'Geyser': { class: 'Elemental', attack: 8, health: 10, emoji: '⛲', elements: ['Lava', 'Water'], tier: 3, startOfCombat: 'deal3AndFreeze' },
  'Volcano': { class: 'Elemental', attack: 12, health: 12, emoji: '🌋', elements: ['Lava', 'Earth'], tier: 3, deathrattle: 'deal4ToAll' },
  'Pyroclastic Flow': { class: 'Elemental', attack: 9, health: 9, emoji: '☄️', elements: ['Lava', 'Air'], tier: 3, startOfCombat: 'deal2AndReduceAttack2' },
  'Steam Engine': { class: 'Elemental', attack: 7, health: 14, emoji: '🚂', elements: ['Steam', 'Fire'], tier: 3, endOfTurn: 'heal2AndArmor1' },
  'Distillery': { class: 'Elemental', attack: 6, health: 10, emoji: '🥃', elements: ['Steam', 'Water'], tier: 3, battlecry: 'heal5' },
  'Hot Spring': { class: 'Elemental', attack: 5, health: 12, emoji: '♨️', elements: ['Steam', 'Earth'], tier: 3, startOfCombat: '+2ArmorAdjacent' },
  'Cloud': { class: 'Elemental', attack: 6, health: 8, emoji: '☁️', elements: ['Steam', 'Air'], tier: 3, stealth: true, deathrattle: 'returnToHand' },
  'Forge': { class: 'Elemental', attack: 11, health: 9, emoji: '⚒️', elements: ['Magma', 'Fire'], tier: 3, startOfCombat: '+2AttackAndTaunt' },
  'Geothermal Plant': { class: 'Elemental', attack: 7, health: 13, emoji: '⚡', elements: ['Magma', 'Water'], tier: 3, startOfCombat: 'summon2/2Geyser' },
  'Lava Field': { class: 'Elemental', attack: 8, health: 15, emoji: '🌋', elements: ['Magma', 'Earth'], tier: 3, deathrattle: 'deal3ToAll' },
  'Ash Cloud': { class: 'Elemental', attack: 6, health: 7, emoji: '🌫️', elements: ['Magma', 'Air'], tier: 3, endOfCombat: 'enemiesLose3Attack' },
  'Plasma Torch': { class: 'Elemental', attack: 12, health: 6, emoji: '🔥', elements: ['Lightning', 'Fire'], tier: 3, windfury: true },
  'Thunderstorm': { class: 'Elemental', attack: 9, health: 11, emoji: '⛈️', elements: ['Lightning', 'Water'], tier: 3, startOfCombat: 'deal5Split' },
  'Electromagnet': { class: 'Elemental', attack: 7, health: 10, emoji: '🧲', elements: ['Lightning', 'Earth'], tier: 3, startOfCombat: 'setHighAttackTo0' },
  'Static Storm': { class: 'Elemental', attack: 8, health: 7, emoji: '⚡', elements: ['Lightning', 'Air'], tier: 3, endOfTurn: '+2AttackRandom' },
  'Steamship': { class: 'Elemental', attack: 6, health: 14, emoji: '🚢', elements: ['Tide', 'Fire'], tier: 3, mech: true, deathrattle: 'refund2Gold' },
  'Ocean': { class: 'Elemental', attack: 5, health: 16, emoji: '🌊', elements: ['Tide', 'Water'], tier: 3, endOfTurn: 'heal3' },
  'Estuary': { class: 'Elemental', attack: 6, health: 12, emoji: '🏖️', elements: ['Tide', 'Earth'], tier: 3, startOfCombat: '+1/+1TwoRandom' },
  'Sea Breeze': { class: 'Elemental', attack: 7, health: 8, emoji: '🌊', elements: ['Tide', 'Air'], tier: 3, windfury: true },
  'Brick Kiln': { class: 'Elemental', attack: 4, health: 15, emoji: '🧱', elements: ['Mud', 'Fire'], tier: 3, taunt: true, endOfCombat: 'summon2/2Brick' },
  'Clay Pottery': { class: 'Elemental', attack: 3, health: 10, emoji: '🏺', elements: ['Mud', 'Water'], tier: 3, endOfTurn: '+1HealthRandom' },
  'Clay': { class: 'Elemental', attack: 2, health: 20, emoji: '🟫', elements: ['Mud', 'Earth'], tier: 3, taunt: true },
  'Dust Mound': { class: 'Elemental', attack: 3, health: 8, emoji: '🏜️', elements: ['Mud', 'Air'], tier: 3, deathrattle: 'summonTwo1/1DustMites' },
  'Sauna': { class: 'Elemental', attack: 4, health: 12, emoji: '🧖', elements: ['Mist', 'Fire'], tier: 3, startOfCombat: '+4Armor' },
  'Dew': { class: 'Elemental', attack: 2, health: 4, emoji: '💧', elements: ['Mist', 'Water'], tier: 3, startOfCombat: 'heal3' },
  'Morning Fog': { class: 'Elemental', attack: 3, health: 10, emoji: '🌅', elements: ['Mist', 'Earth'], tier: 3, startOfCombat: 'stealthAll' },
  'Vapor Cloud': { class: 'Elemental', attack: 5, health: 7, emoji: '☁️', elements: ['Mist', 'Air'], tier: 3, deathrattle: '+3Armor' },
  'Glass': { class: 'Elemental', attack: 8, health: 3, emoji: '🔮', elements: ['Stone', 'Fire'], tier: 3, divineShield: true, deathrattle: 'deal8Random' },
  'Marble': { class: 'Elemental', attack: 2, health: 12, emoji: '🎱', elements: ['Stone', 'Water'], tier: 3, endOfCombat: 'drawCard' },
  'Boulder': { class: 'Elemental', attack: 5, health: 16, emoji: '🪨', elements: ['Stone', 'Earth'], tier: 3, taunt: true },
  'Sandstone': { class: 'Elemental', attack: 4, health: 10, emoji: '🏜️', elements: ['Stone', 'Air'], tier: 3, startOfCombat: '+1ArmorAdjacent' },
  'Ember Ash': { class: 'Elemental', attack: 7, health: 5, emoji: '🔥', elements: ['Dust', 'Fire'], tier: 3, deathrattle: 'deal3Split' },
  'Silt': { class: 'Elemental', attack: 3, health: 12, emoji: '🟫', elements: ['Dust', 'Water'], tier: 3, startOfCombat: 'removeWindfury' },
  'Sand': { class: 'Elemental', attack: 4, health: 8, emoji: '🏜️', elements: ['Dust', 'Earth'], tier: 3, startOfCombat: 'deal1ToAll' },
  'Dust Devil': { class: 'Elemental', attack: 6, health: 6, emoji: '🌪️', elements: ['Dust', 'Air'], tier: 3, windfury: true },
  'Fire Whirl': { class: 'Elemental', attack: 10, health: 10, emoji: '🌪️🔥', elements: ['Gale', 'Fire'], tier: 3, windfury: true, deathrattle: 'deal5Random' },
  'Sea Spray': { class: 'Elemental', attack: 3, health: 8, emoji: '💦', elements: ['Gale', 'Water'], tier: 3, afterAttack: 'heal2' },
  'Dust Storm': { class: 'Elemental', attack: 6, health: 7, emoji: '🌪️💨', elements: ['Gale', 'Earth'], tier: 3, startOfCombat: 'reduceAttack2' },
  'Tornado': { class: 'Elemental', attack: 7, health: 9, emoji: '🌪️', elements: ['Gale', 'Air'], tier: 3, startOfCombat: 'shuffleEnemyPositions' },
  'Robot Arm': { class: 'Tech', attack: 5, health: 10, emoji: '🦾', elements: ['Android', 'Gear'], tier: 3, mech: true, afterPlayMech: '+2Attack' },
  'Drone': { class: 'Tech', attack: 4, health: 5, emoji: '🛸', elements: ['Android', 'Chip'], tier: 3, stealth: true, deathrattle: 'drawCard' },
  'Gearbox': { class: 'Tech', attack: 6, health: 8, emoji: '⚙️', elements: ['Automaton', 'Gear'], tier: 3, mech: true, endOfTurn: '+1/+1OtherMechs' },
  'Smartwatch': { class: 'Tech', attack: 3, health: 6, emoji: '⌚', elements: ['Automaton', 'Chip'], tier: 3, startOfCombat: 'gain1Gold' },
  'Mechatronics': { class: 'Tech', attack: 7, health: 9, emoji: '🤖⚙️', elements: ['AI Core', 'Gear'], tier: 3, mech: true, startOfCombat: 'enemiesLose1Attack' },
  'Microprocessor': { class: 'Tech', attack: 2, health: 4, emoji: '💻', elements: ['AI Core', 'Chip'], tier: 3, startOfCombat: 'discoverTechUnit' },
  
  // Tier 4 Units (Tier2+Tier2 combinations) - Legendary tier
  'Sun': { class: 'Elemental', attack: 18, health: 18, emoji: '☀️', elements: ['Lava', 'Lava'], tier: 4, startOfCombat: 'deal5ToAll' },
  'Sulfur': { class: 'Elemental', attack: 12, health: 16, emoji: '🟡', elements: ['Lava', 'Steam'], tier: 4, deathrattle: 'poisonAll' },
  'Caldera': { class: 'Elemental', attack: 14, health: 14, emoji: '🌋', elements: ['Lava', 'Magma'], tier: 4, startOfCombat: 'deal4AndReduceAttack1' },
  'Conflagration': { class: 'Elemental', attack: 16, health: 12, emoji: '🔥', elements: ['Lava', 'Smoke'], tier: 4, endOfTurn: 'deal3ToAll' },
  'Pumice': { class: 'Elemental', attack: 8, health: 20, emoji: '🪨', elements: ['Lava', 'Tide'], tier: 4, spellImmune: true },
  'Ceramic': { class: 'Elemental', attack: 9, health: 18, emoji: '🏺', elements: ['Lava', 'Mud'], tier: 4, taunt: true, endOfCombat: 'healAdjacent5' },
  'Rainbow': { class: 'Elemental', attack: 10, health: 10, emoji: '🌈', elements: ['Lava', 'Mist'], tier: 4, battlecry: 'healAll5' },
  'Steel': { class: 'Elemental', attack: 15, health: 15, emoji: '⚔️', elements: ['Lava', 'Stone'], tier: 4, armor: true },
  'Volcanic Lightning': { class: 'Elemental', attack: 17, health: 13, emoji: '⚡🌋', elements: ['Lava', 'Sandstorm'], tier: 4, startOfCombat: 'deal3RandomAndBurn' },
  'Blaze': { class: 'Elemental', attack: 20, health: 12, emoji: '🔥', elements: ['Lava', 'Gale'], tier: 4, windfury: true, deathrattle: 'deal4Random' },
  'Cloudburst': { class: 'Elemental', attack: 12, health: 18, emoji: '☁️', elements: ['Steam', 'Steam'], tier: 4, startOfCombat: 'deal6Spread' },
  'Mud Volcano': { class: 'Elemental', attack: 10, health: 20, emoji: '🌋', elements: ['Steam', 'Magma'], tier: 4, endOfCombat: 'summon3/3MudGolem' },
  'Thunderstorm': { class: 'Elemental', attack: 18, health: 14, emoji: '⛈️', elements: ['Steam', 'Smoke'], tier: 4, windfury: true, afterAttack: 'heal2' },
  'Scalding Water': { class: 'Elemental', attack: 16, health: 12, emoji: '♨️', elements: ['Steam', 'Tide'], tier: 4, deathrattle: 'deal3Adjacent' },
  'Mudslide': { class: 'Elemental', attack: 15, health: 15, emoji: '🏔️', elements: ['Steam', 'Mud'], tier: 4, startOfCombat: 'pullAndStun' },
  'Sunshower': { class: 'Elemental', attack: 12, health: 16, emoji: '🌦️', elements: ['Steam', 'Mist'], tier: 4, startOfCombat: '+1/+1PerWater' },
  'Steam Vent': { class: 'Elemental', attack: 8, health: 20, emoji: '♨️', elements: ['Steam', 'Stone'], tier: 4, endOfTurn: 'summon2/2SteamSprite' },
  'Haboob': { class: 'Elemental', attack: 10, health: 14, emoji: '🌪️', elements: ['Steam', 'Sandstorm'], tier: 4, startOfCombat: 'removeTaunt' },
  'Supercell': { class: 'Elemental', attack: 14, health: 16, emoji: '⛈️', elements: ['Steam', 'Gale'], tier: 4, startOfCombat: 'summonStormElementals' },
  'Supervolcano': { class: 'Elemental', attack: 20, health: 20, emoji: '🌋', elements: ['Magma', 'Magma'], tier: 4, endOfCombat: 'deal7ToAll' },
  'Pyroclastic Flow': { class: 'Elemental', attack: 18, health: 18, emoji: '☄️', elements: ['Magma', 'Smoke'], tier: 4, startOfCombat: 'deal8ToAll' },
  'Island': { class: 'Elemental', attack: 14, health: 22, emoji: '🏝️', elements: ['Magma', 'Tide'], tier: 4, endOfCombat: 'summon2/2LavaElemental' },
  'Lahar': { class: 'Elemental', attack: 16, health: 14, emoji: '🌋', elements: ['Magma', 'Mud'], tier: 4, startOfCombat: 'deal4ToAll' },
  'Jungle': { class: 'Elemental', attack: 12, health: 20, emoji: '🌴', elements: ['Magma', 'Mist'], tier: 4, endOfCombat: 'healAll4' },
  'Forge': { class: 'Elemental', attack: 18, health: 18, emoji: '⚒️', elements: ['Magma', 'Stone'], tier: 4, startOfCombat: '+2AttackWeapons' },
  'Scorched Earth': { class: 'Elemental', attack: 17, health: 15, emoji: '🔥', elements: ['Magma', 'Sandstorm'], tier: 4, passive: 'damageOnMove' },
  'Ashfall': { class: 'Elemental', attack: 14, health: 17, emoji: '🌋', elements: ['Magma', 'Gale'], tier: 4, endOfCombat: 'reduceAttack3' },
  'Firenado': { class: 'Elemental', attack: 20, health: 14, emoji: '🔥🌪️', elements: ['Smoke', 'Smoke'], tier: 4, windfury: true, startOfCombat: 'deal5Adjacent' },
  'Waterspout': { class: 'Elemental', attack: 13, health: 17, emoji: '🌊', elements: ['Smoke', 'Tide'], tier: 4, startOfCombat: 'liftAndDamage3' },
  'Life': { class: 'Elemental', attack: 12, health: 22, emoji: '🌱', elements: ['Smoke', 'Mud'], tier: 4, endOfCombat: 'healAll5' },
  'Acid Rain': { class: 'Elemental', attack: 10, health: 16, emoji: '🌧️', elements: ['Smoke', 'Mist'], tier: 4, endOfCombat: 'erodeArmor4' },
  'Meteor': { class: 'Elemental', attack: 20, health: 10, emoji: '☄️', elements: ['Smoke', 'Stone'], tier: 4, battlecry: 'deal10Random' },
  'Mirage': { class: 'Elemental', attack: 8, health: 18, emoji: '🌅', elements: ['Smoke', 'Sandstorm'], tier: 4, startOfCombat: 'miss50Percent' },
  'Ember': { class: 'Elemental', attack: 14, health: 12, emoji: '🔥', elements: ['Smoke', 'Gale'], tier: 4, endOfCombat: 'deal2ToAll' },
  'Ocean': { class: 'Elemental', attack: 16, health: 16, emoji: '🌊', elements: ['Tide', 'Tide'], tier: 4, endOfTurn: 'heal4' },
  'Marsh': { class: 'Elemental', attack: 12, health: 18, emoji: '🌾', elements: ['Tide', 'Mud'], tier: 4, startOfCombat: 'poisonAll' },
  'Downpour': { class: 'Elemental', attack: 14, health: 14, emoji: '🌧️', elements: ['Tide', 'Mist'], tier: 4, endOfCombat: 'slowEnemies' },
  'Canyon': { class: 'Elemental', attack: 13, health: 17, emoji: '🏔️', elements: ['Tide', 'Stone'], tier: 4, startOfCombat: 'divideEnemies' },
  'Flash Flood': { class: 'Elemental', attack: 18, health: 18, emoji: '🌊', elements: ['Tide', 'Sandstorm'], tier: 4, startOfCombat: 'deal6ToAll' },
  'Squall': { class: 'Elemental', attack: 15, health: 15, emoji: '🌊', elements: ['Tide', 'Gale'], tier: 4, startOfCombat: 'stunAll1Turn' },
  'Bog': { class: 'Elemental', attack: 12, health: 20, emoji: '🌾', elements: ['Mud', 'Mud'], tier: 4, endOfCombat: 'poisonDamage3' },
  'Mire': { class: 'Elemental', attack: 13, health: 17, emoji: '🌾', elements: ['Mud', 'Mist'], tier: 4, startOfCombat: 'trap1Turn' },
  'Clay': { class: 'Elemental', attack: 14, health: 18, emoji: '🟫', elements: ['Mud', 'Stone'], tier: 4, adaptiveDefense: true },
  'Badlands': { class: 'Elemental', attack: 15, health: 15, emoji: '🏜️', elements: ['Mud', 'Sandstorm'], tier: 4, passive: 'reduceRanged50' },
  'Dust Storm': { class: 'Elemental', attack: 16, health: 14, emoji: '🌪️', elements: ['Mud', 'Gale'], tier: 4, startOfCombat: 'blindEnemies' },
  'Fogbank': { class: 'Elemental', attack: 10, health: 22, emoji: '🌫️', elements: ['Mist', 'Mist'], tier: 4, passive: 'protectBackline' },
  'Avalanche': { class: 'Elemental', attack: 18, health: 18, emoji: '🏔️', elements: ['Mist', 'Stone'], tier: 4, startOfCombat: 'deal7Cone' },
  'Mud Rain': { class: 'Elemental', attack: 12, health: 16, emoji: '🌧️', elements: ['Mist', 'Sandstorm'], tier: 4, startOfCombat: 'slow3For2Turns' },
  'Hailstorm': { class: 'Elemental', attack: 16, health: 12, emoji: '🧊', elements: ['Mist', 'Gale'], tier: 4, endOfCombat: 'freezeDamaged' },
  'Mountain': { class: 'Elemental', attack: 20, health: 25, emoji: '🏔️', elements: ['Stone', 'Stone'], tier: 4, taunt: true, laughAtDamage: true },
  'Sandstone': { class: 'Elemental', attack: 14, health: 20, emoji: '🏜️', elements: ['Stone', 'Sandstorm'], tier: 4, passive: 'reducePhysical3' },
  'Plateau': { class: 'Elemental', attack: 15, health: 22, emoji: '🏔️', elements: ['Stone', 'Gale'], tier: 4, startOfCombat: '+2Health+1Attack' },
  'Desert': { class: 'Elemental', attack: 13, health: 18, emoji: '🏜️', elements: ['Sandstorm', 'Sandstorm'], tier: 4, endOfTurn: 'dehydrate2' },
  'Drought': { class: 'Elemental', attack: 12, health: 19, emoji: '🏜️', elements: ['Sandstorm', 'Gale'], tier: 4, passive: 'weakenWater3' },
  'Tempest': { class: 'Elemental', attack: 19, health: 19, emoji: '🌪️', elements: ['Gale', 'Gale'], tier: 4, startOfCombat: 'randomBuffAllies' },
  'Colossus': { class: 'Tech', attack: 20, health: 20, emoji: '🤖', elements: ['Android', 'Android'], tier: 4, taunt: true, deathrattle: 'deal5ToAll' },
  'Overlord': { class: 'Tech', attack: 18, health: 18, emoji: '🤖', elements: ['Android', 'Automaton'], tier: 4, startOfCombat: '+2/+2AllMechs' },
  'Synth': { class: 'Tech', attack: 17, health: 17, emoji: '🤖', elements: ['Android', 'AI Core'], tier: 4, endOfCombat: 'learnEnemyAbility' },
  'Factory': { class: 'Tech', attack: 16, health: 20, emoji: '🏭', elements: ['Automaton', 'Automaton'], tier: 4, endOfTurn: 'spawnTwo1/1Droids' },
  'Hive Mind': { class: 'Tech', attack: 18, health: 18, emoji: '🧠', elements: ['Automaton', 'AI Core'], tier: 4, startOfCombat: 'doubleBattlecries' },
  'Singularity': { class: 'Tech', attack: 20, health: 20, emoji: '⚫', elements: ['AI Core', 'AI Core'], tier: 4, passive: 'copyRandomAbilities' }
};

// Fusion mapping system
const FUSION_MAP = {
  // Tier1 + Tier1 = Tier2
  'Fire+Fire': 'Lava', 'Water+Water': 'Tide', 'Earth+Earth': 'Stone', 'Air+Air': 'Gale',
  'Fire+Water': 'Steam', 'Water+Fire': 'Steam', 'Fire+Earth': 'Magma', 'Earth+Fire': 'Magma',
  'Fire+Air': 'Smoke', 'Air+Fire': 'Smoke', 'Water+Earth': 'Mud', 'Earth+Water': 'Mud',
  'Water+Air': 'Mist', 'Air+Water': 'Mist', 'Earth+Air': 'Sandstorm', 'Air+Earth': 'Sandstorm',
  'Gear+Gear': 'Android', 'Chip+Chip': 'AI Core', 'Gear+Chip': 'Automaton', 'Chip+Gear': 'Automaton',
  
  // Tier2 + Tier1 = Tier3
  'Lava+Fire': 'Foundry', 'Lava+Water': 'Geyser', 'Lava+Earth': 'Volcano', 'Lava+Air': 'Pyroclastic Flow',
  'Steam+Fire': 'Steam Engine', 'Steam+Water': 'Distillery', 'Steam+Earth': 'Hot Spring', 'Steam+Air': 'Cloud',
  'Magma+Fire': 'Forge', 'Magma+Water': 'Geothermal Plant', 'Magma+Earth': 'Lava Field', 'Magma+Air': 'Ash Cloud',
  'Lightning+Fire': 'Plasma Torch', 'Lightning+Water': 'Thunderstorm', 'Lightning+Earth': 'Electromagnet', 'Lightning+Air': 'Static Storm',
  'Tide+Fire': 'Steamship', 'Tide+Water': 'Ocean', 'Tide+Earth': 'Estuary', 'Tide+Air': 'Sea Breeze',
  'Mud+Fire': 'Brick Kiln', 'Mud+Water': 'Clay Pottery', 'Mud+Earth': 'Clay', 'Mud+Air': 'Dust Mound',
  'Mist+Fire': 'Sauna', 'Mist+Water': 'Dew', 'Mist+Earth': 'Morning Fog', 'Mist+Air': 'Vapor Cloud',
  'Stone+Fire': 'Glass', 'Stone+Water': 'Marble', 'Stone+Earth': 'Boulder', 'Stone+Air': 'Sandstone',
  'Dust+Fire': 'Ember Ash', 'Dust+Water': 'Silt', 'Dust+Earth': 'Sand', 'Dust+Air': 'Dust Devil',
  'Gale+Fire': 'Fire Whirl', 'Gale+Water': 'Sea Spray', 'Gale+Earth': 'Dust Storm', 'Gale+Air': 'Tornado',
  'Android+Gear': 'Robot Arm', 'Android+Chip': 'Drone', 'Automaton+Gear': 'Gearbox', 'Automaton+Chip': 'Smartwatch',
  'AI Core+Gear': 'Mechatronics', 'AI Core+Chip': 'Microprocessor',
  
  // Tier2 + Tier2 = Tier4 (Legendary)
  'Lava+Lava': 'Sun', 'Lava+Steam': 'Sulfur', 'Lava+Magma': 'Caldera', 'Lava+Smoke': 'Conflagration',
  'Lava+Tide': 'Pumice', 'Lava+Mud': 'Ceramic', 'Lava+Mist': 'Rainbow', 'Lava+Stone': 'Steel',
  'Lava+Sandstorm': 'Volcanic Lightning', 'Lava+Gale': 'Blaze', 'Steam+Steam': 'Cloudburst',
  'Steam+Magma': 'Mud Volcano', 'Steam+Smoke': 'Thunderstorm', 'Steam+Tide': 'Scalding Water',
  'Steam+Mud': 'Mudslide', 'Steam+Mist': 'Sunshower', 'Steam+Stone': 'Steam Vent',
  'Steam+Sandstorm': 'Haboob', 'Steam+Gale': 'Supercell', 'Magma+Magma': 'Supervolcano',
  'Magma+Smoke': 'Pyroclastic Flow', 'Magma+Tide': 'Island', 'Magma+Mud': 'Lahar',
  'Magma+Mist': 'Jungle', 'Magma+Stone': 'Forge', 'Magma+Sandstorm': 'Scorched Earth',
  'Magma+Gale': 'Ashfall', 'Smoke+Smoke': 'Firenado', 'Smoke+Tide': 'Waterspout',
  'Smoke+Mud': 'Life', 'Smoke+Mist': 'Acid Rain', 'Smoke+Stone': 'Meteor',
  'Smoke+Sandstorm': 'Mirage', 'Smoke+Gale': 'Ember', 'Tide+Tide': 'Ocean',
  'Tide+Mud': 'Marsh', 'Tide+Mist': 'Downpour', 'Tide+Stone': 'Canyon',
  'Tide+Sandstorm': 'Flash Flood', 'Tide+Gale': 'Squall', 'Mud+Mud': 'Bog',
  'Mud+Mist': 'Mire', 'Mud+Stone': 'Clay', 'Mud+Sandstorm': 'Badlands',
  'Mud+Gale': 'Dust Storm', 'Mist+Mist': 'Fogbank', 'Mist+Stone': 'Avalanche',
  'Mist+Sandstorm': 'Mud Rain', 'Mist+Gale': 'Hailstorm', 'Stone+Stone': 'Mountain',
  'Stone+Sandstorm': 'Sandstone', 'Stone+Gale': 'Plateau', 'Sandstorm+Sandstorm': 'Desert',
  'Sandstorm+Gale': 'Drought', 'Gale+Gale': 'Tempest', 'Android+Android': 'Colossus',
  'Android+Automaton': 'Overlord', 'Android+AI Core': 'Synth', 'Automaton+Automaton': 'Factory',
  'Automaton+AI Core': 'Hive Mind', 'AI Core+AI Core': 'Singularity'
};

// Export the new system
export { NEW_UNIT_DEFINITIONS, FUSION_MAP, BASE_TIER1_UNITS }; 